import type { ContentItem, ContentKind } from "./types.js";
import { computeContentStats } from "./stats.js";

function sectionForKind(kind: ContentKind, items: ContentItem[]): string {
  const subset = items.filter((item) => item.kind === kind);
  if (subset.length === 0) {
    return "";
  }

  const heading =
    kind === "article"
      ? "Articles"
      : kind === "note"
        ? "Notes"
        : kind === "thesis"
          ? "Theses"
          : "Chat exports";

  const lines = subset.map(
    (item) =>
      `- **${item.title}** (\`${item.id}\`) — ${item.summary}${item.tags.length > 0 ? ` · _${item.tags.join(", ")}_` : ""}`,
  );

  return `## ${heading}\n\n${lines.join("\n")}\n`;
}

export function renderContentDigest(
  items: ContentItem[],
  generatedAt = new Date(),
): string {
  const stats = computeContentStats(items);
  const stamp = generatedAt.toISOString().slice(0, 10);

  const kindLines = Object.entries(stats.byKind)
    .filter(([, count]) => count > 0)
    .map(([kind, count]) => `- ${kind}: ${count}`)
    .join("\n");

  const topTags = stats.tags
    .slice(0, 12)
    .map((entry) => `- ${entry.tag} (${entry.count})`)
    .join("\n");

  const sections = (
    ["article", "note", "thesis", "chat-export"] as ContentKind[]
  )
    .map((kind) => sectionForKind(kind, items))
    .filter(Boolean)
    .join("\n");

  return `# Fleekelon content digest

Generated: ${stamp}

## Snapshot

- total items: ${stats.total}
- with PDF companion: ${stats.withPdf}

### By kind

${kindLines || "- (empty)"}

### Top tags

${topTags || "- (none)"}

${sections}
---

<sub>Generated by \`fleekelon content digest\`.</sub>
`;
}
