export type SiteEntry = {
  id: string;
  title: string;
  kind: string;
  kindLabel: string;
  summary: string;
  tags: string[];
  href: string;
};

export type HomePageInput = {
  name: string;
  tagline: string;
  location: string;
  highlights: string[];
  links: Array<{ label: string; url: string }>;
  entries: SiteEntry[];
};

export type ArticlePageInput = {
  title: string;
  kindLabel: string;
  summary: string;
  tags: string[];
  bodyHtml: string;
  sourcePath: string;
};

function escapeHtml(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}

function shell(options: {
  title: string;
  description: string;
  bodyClass: string;
  body: string;
}): string {
  return `<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${escapeHtml(options.title)}</title>
  <meta name="description" content="${escapeHtml(options.description)}" />
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="https://fonts.googleapis.com/css2?family=Bricolage+Grotesque:opsz,wght@12..96,500;12..96,700;12..96,800&family=Sora:wght@300;400;500;600&display=swap" rel="stylesheet" />
  <link rel="stylesheet" href="styles.css" />
</head>
<body class="${options.bodyClass}">
${options.body}
  <script src="site.js" defer></script>
</body>
</html>
`;
}

export function renderHomePage(input: HomePageInput): string {
  const writing = input.entries
    .map(
      (entry, index) => `
        <a class="writing-row" href="${escapeHtml(entry.href)}" style="--i:${index}">
          <span class="writing-meta">
            <span class="writing-kind">${escapeHtml(entry.kindLabel)}</span>
            <span class="writing-id">${escapeHtml(entry.id)}</span>
          </span>
          <span class="writing-main">
            <span class="writing-title">${escapeHtml(entry.title)}</span>
            <span class="writing-summary">${escapeHtml(entry.summary)}</span>
          </span>
        </a>`,
    )
    .join("\n");

  const highlightLines = input.highlights
    .map((item) => `<li>${escapeHtml(item)}</li>`)
    .join("\n");

  const linkLines = input.links
    .filter((link) => !link.url.startsWith("sites/"))
    .map(
      (link) =>
        `<a href="${escapeHtml(link.url)}">${escapeHtml(link.label)}</a>`,
    )
    .join("\n");

  const body = `
  <div class="atmosphere" aria-hidden="true">
    <div class="atmosphere-wash"></div>
    <div class="atmosphere-grain"></div>
  </div>

  <header class="topbar">
    <a class="topbar-brand" href="#top">fleekelon</a>
    <nav class="topbar-nav">
      <a href="#writing">Writing</a>
      <a href="#now">Now</a>
      <a href="#links">Links</a>
    </nav>
  </header>

  <main id="top">
    <section class="hero">
      <div class="hero-plane" aria-hidden="true"></div>
      <div class="hero-copy">
        <p class="hero-brand">fleekelon</p>
        <h1>${escapeHtml(input.name)}</h1>
        <p class="hero-lead">${escapeHtml(input.tagline)}</p>
        <div class="hero-actions">
          <a class="btn btn-primary" href="#writing">Read the writing</a>
          <a class="btn btn-ghost" href="https://github.com/fleekelon/fleekelon">Open the toolkit</a>
        </div>
        <p class="hero-location">${escapeHtml(input.location)}</p>
      </div>
    </section>

    <section class="section" id="writing">
      <div class="section-head">
        <h2>Writing</h2>
        <p>Frameworks, notes, and archived conversations from the personal content catalog.</p>
      </div>
      <div class="writing-list">
        ${writing || `<p class="empty">No published pieces yet.</p>`}
      </div>
    </section>

    <section class="section section-split" id="now">
      <div class="section-head">
        <h2>Now</h2>
        <p>What this system is being built to hold.</p>
      </div>
      <ul class="now-list">
        ${highlightLines}
      </ul>
    </section>

    <section class="section" id="links">
      <div class="section-head">
        <h2>Links</h2>
        <p>Elsewhere on the map.</p>
      </div>
      <div class="link-row">
        ${linkLines}
      </div>
    </section>
  </main>

  <footer class="footer">
    <p>Generated by the fleekelon personal toolkit · content catalog as source of truth</p>
  </footer>
`;

  return shell({
    title: `${input.name} · fleekelon`,
    description: input.tagline,
    bodyClass: "page-home",
    body,
  });
}

export function renderArticlePage(input: ArticlePageInput): string {
  const tags =
    input.tags.length > 0
      ? `<p class="article-tags">${input.tags.map((tag) => escapeHtml(tag)).join(" · ")}</p>`
      : "";

  const body = `
  <div class="atmosphere atmosphere-quiet" aria-hidden="true">
    <div class="atmosphere-wash"></div>
    <div class="atmosphere-grain"></div>
  </div>

  <header class="topbar">
    <a class="topbar-brand" href="index.html">fleekelon</a>
    <nav class="topbar-nav">
      <a href="index.html#writing">Writing</a>
      <a href="index.html#now">Now</a>
    </nav>
  </header>

  <main class="article-shell">
    <a class="back-link" href="index.html#writing">← Back to writing</a>
    <p class="article-kind">${escapeHtml(input.kindLabel)}</p>
    <h1 class="article-title">${escapeHtml(input.title)}</h1>
    <p class="article-summary">${escapeHtml(input.summary)}</p>
    ${tags}
    <article class="article-body">
      ${input.bodyHtml}
    </article>
    <p class="article-source">Source: <code>${escapeHtml(input.sourcePath)}</code></p>
  </main>

  <footer class="footer">
    <p><a href="index.html">fleekelon</a> · personal content OS</p>
  </footer>
`;

  return shell({
    title: `${input.title} · fleekelon`,
    description: input.summary,
    bodyClass: "page-article",
    body,
  });
}

export const siteAssets: Record<string, string> = {
  "styles.css": `/* fleekelon personal site — ink mist */
:root {
  --ink: #07110f;
  --ink-2: #0f1c18;
  --mist: #d9e2dd;
  --mist-dim: rgba(217, 226, 221, 0.72);
  --jade: #7aa894;
  --brass: #c2a46a;
  --line: rgba(217, 226, 221, 0.14);
  --font-display: "Bricolage Grotesque", Georgia, serif;
  --font-body: "Sora", "Segoe UI", sans-serif;
  --space: clamp(1.25rem, 3vw, 2.5rem);
  --max: 72rem;
}

* { box-sizing: border-box; }
html { scroll-behavior: smooth; }
body {
  margin: 0;
  min-height: 100vh;
  color: var(--mist);
  background: var(--ink);
  font-family: var(--font-body);
  font-weight: 400;
  line-height: 1.6;
  text-rendering: optimizeLegibility;
}

a { color: inherit; text-decoration-thickness: 1px; text-underline-offset: 0.22em; }
a:hover { color: var(--jade); }

.atmosphere {
  position: fixed;
  inset: 0;
  z-index: -2;
  pointer-events: none;
  overflow: hidden;
}
.atmosphere-wash {
  position: absolute;
  inset: -20%;
  background:
    radial-gradient(ellipse 80% 55% at 18% 18%, rgba(122, 168, 148, 0.22), transparent 55%),
    radial-gradient(ellipse 70% 50% at 82% 8%, rgba(194, 164, 106, 0.12), transparent 50%),
    radial-gradient(ellipse 90% 70% at 50% 100%, rgba(15, 40, 34, 0.95), transparent 60%),
    linear-gradient(160deg, #07110f 0%, #10221c 45%, #07110f 100%);
  animation: drift 18s ease-in-out infinite alternate;
}
.atmosphere-quiet .atmosphere-wash {
  opacity: 0.72;
  animation-duration: 28s;
}
.atmosphere-grain {
  position: absolute;
  inset: 0;
  opacity: 0.16;
  background-image: url("data:image/svg+xml,%3Csvg viewBox='0 0 200 200' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.85' numOctaves='2' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)' opacity='0.55'/%3E%3C/svg%3E");
  mix-blend-mode: soft-light;
}

@keyframes drift {
  from { transform: translate3d(-1.5%, -1%, 0) scale(1.02); }
  to { transform: translate3d(1.5%, 1.2%, 0) scale(1.06); }
}

.topbar {
  position: sticky;
  top: 0;
  z-index: 10;
  display: flex;
  justify-content: space-between;
  align-items: center;
  gap: 1rem;
  padding: 1rem var(--space);
  backdrop-filter: blur(14px);
  background: rgba(7, 17, 15, 0.55);
  border-bottom: 1px solid transparent;
}
.topbar-brand {
  font-family: var(--font-display);
  font-weight: 700;
  letter-spacing: 0.08em;
  text-transform: lowercase;
  text-decoration: none;
  font-size: 0.95rem;
}
.topbar-nav {
  display: flex;
  gap: 1.25rem;
  font-size: 0.85rem;
  color: var(--mist-dim);
}
.topbar-nav a { text-decoration: none; }

.hero {
  position: relative;
  min-height: 100svh;
  display: grid;
  align-items: end;
  padding: clamp(4rem, 12vh, 7rem) var(--space) clamp(3rem, 8vh, 5rem);
  overflow: hidden;
}
.hero-plane {
  position: absolute;
  inset: 0;
  z-index: -1;
  background:
    linear-gradient(180deg, rgba(7, 17, 15, 0.15) 0%, rgba(7, 17, 15, 0.55) 45%, rgba(7, 17, 15, 0.92) 100%),
    url("assets/hero-hangzhou.jpg") center/cover no-repeat;
  transform: scale(1.04);
  animation: hero-breathe 22s ease-in-out infinite alternate;
}
@keyframes hero-breathe {
  from { transform: scale(1.02) translateY(0); }
  to { transform: scale(1.07) translateY(-1.5%); }
}

.hero-copy {
  max-width: 44rem;
  opacity: 0;
  transform: translateY(28px);
  animation: rise 1.1s cubic-bezier(0.22, 1, 0.36, 1) 0.15s forwards;
}
@keyframes rise {
  to { opacity: 1; transform: translateY(0); }
}

.hero-brand {
  margin: 0 0 1rem;
  font-family: var(--font-display);
  font-size: clamp(3.4rem, 11vw, 7.5rem);
  font-weight: 800;
  line-height: 0.9;
  letter-spacing: -0.04em;
  color: var(--mist);
}
.hero h1 {
  margin: 0;
  font-family: var(--font-display);
  font-size: clamp(1.4rem, 3.2vw, 2rem);
  font-weight: 600;
  letter-spacing: -0.02em;
}
.hero-lead {
  margin: 1rem 0 0;
  max-width: 34rem;
  color: var(--mist-dim);
  font-size: clamp(1rem, 2vw, 1.15rem);
  font-weight: 300;
}
.hero-actions {
  display: flex;
  flex-wrap: wrap;
  gap: 0.85rem;
  margin-top: 1.75rem;
}
.hero-location {
  margin: 1.5rem 0 0;
  color: rgba(217, 226, 221, 0.5);
  font-size: 0.85rem;
  letter-spacing: 0.04em;
}

.btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  min-height: 2.75rem;
  padding: 0.7rem 1.2rem;
  border: 1px solid var(--line);
  font-size: 0.92rem;
  text-decoration: none;
  transition: border-color 180ms ease, color 180ms ease, background 180ms ease;
}
.btn-primary {
  background: var(--mist);
  color: var(--ink);
  border-color: var(--mist);
}
.btn-primary:hover { background: #fff; color: var(--ink); }
.btn-ghost { color: var(--mist); }
.btn-ghost:hover { border-color: var(--jade); color: var(--jade); }

.section {
  width: min(100% - (var(--space) * 2), var(--max));
  margin: 0 auto;
  padding: clamp(3.5rem, 9vh, 6rem) 0;
  border-top: 1px solid var(--line);
}
.section-head {
  max-width: 36rem;
  margin-bottom: 2rem;
}
.section-head h2 {
  margin: 0;
  font-family: var(--font-display);
  font-size: clamp(1.8rem, 4vw, 2.6rem);
  letter-spacing: -0.03em;
}
.section-head p {
  margin: 0.75rem 0 0;
  color: var(--mist-dim);
}

.writing-list {
  display: grid;
  gap: 0;
}
.writing-row {
  display: grid;
  grid-template-columns: minmax(7rem, 10rem) 1fr;
  gap: 1.25rem;
  padding: 1.35rem 0;
  border-top: 1px solid var(--line);
  text-decoration: none;
  opacity: 0;
  transform: translateY(16px);
  transition: color 160ms ease;
}
.writing-row:last-child { border-bottom: 1px solid var(--line); }
.writing-row.is-in { opacity: 1; transform: translateY(0); transition: opacity 700ms cubic-bezier(0.22,1,0.36,1), transform 700ms cubic-bezier(0.22,1,0.36,1); transition-delay: calc(var(--i) * 60ms); }
.writing-meta {
  display: flex;
  flex-direction: column;
  gap: 0.35rem;
  padding-top: 0.2rem;
  color: rgba(217, 226, 221, 0.45);
  font-size: 0.75rem;
  letter-spacing: 0.08em;
  text-transform: uppercase;
}
.writing-title {
  display: block;
  font-family: var(--font-display);
  font-size: clamp(1.2rem, 2.4vw, 1.55rem);
  font-weight: 600;
  letter-spacing: -0.02em;
  line-height: 1.25;
}
.writing-summary {
  display: block;
  margin-top: 0.45rem;
  color: var(--mist-dim);
  font-size: 0.95rem;
  font-weight: 300;
}
.writing-row:hover .writing-title { color: var(--jade); }

.now-list {
  margin: 0;
  padding: 0;
  list-style: none;
  display: grid;
  gap: 1rem;
  max-width: 42rem;
}
.now-list li {
  padding-left: 1rem;
  border-left: 2px solid var(--brass);
  color: var(--mist-dim);
}

.link-row {
  display: flex;
  flex-wrap: wrap;
  gap: 1.5rem 2rem;
  font-family: var(--font-display);
  font-size: 1.15rem;
}
.link-row a { text-decoration: none; border-bottom: 1px solid var(--line); padding-bottom: 0.15rem; }

.footer {
  width: min(100% - (var(--space) * 2), var(--max));
  margin: 0 auto;
  padding: 2rem 0 3rem;
  color: rgba(217, 226, 221, 0.4);
  font-size: 0.8rem;
  border-top: 1px solid var(--line);
}

.article-shell {
  width: min(100% - (var(--space) * 2), 48rem);
  margin: 0 auto;
  padding: clamp(2rem, 6vh, 3.5rem) 0 4rem;
}
.back-link {
  display: inline-block;
  margin-bottom: 1.5rem;
  color: var(--mist-dim);
  text-decoration: none;
  font-size: 0.9rem;
}
.article-kind {
  margin: 0;
  color: var(--brass);
  letter-spacing: 0.12em;
  text-transform: uppercase;
  font-size: 0.75rem;
}
.article-title {
  margin: 0.6rem 0 0;
  font-family: var(--font-display);
  font-size: clamp(2rem, 5vw, 3rem);
  line-height: 1.15;
  letter-spacing: -0.03em;
}
.article-summary {
  margin: 1rem 0 0;
  color: var(--mist-dim);
  font-size: 1.05rem;
  font-weight: 300;
}
.article-tags {
  margin: 1rem 0 0;
  color: rgba(217, 226, 221, 0.45);
  font-size: 0.85rem;
}
.article-body {
  margin-top: 2.5rem;
  font-size: 1.02rem;
}
.article-body :is(h1,h2,h3,h4) {
  font-family: var(--font-display);
  letter-spacing: -0.02em;
  line-height: 1.25;
  margin: 2rem 0 0.8rem;
}
.article-body h1 { font-size: 1.8rem; }
.article-body h2 { font-size: 1.45rem; }
.article-body h3 { font-size: 1.2rem; }
.article-body p { margin: 0 0 1rem; color: var(--mist-dim); }
.article-body li { margin: 0.35rem 0; color: var(--mist-dim); }
.article-body strong { color: var(--mist); font-weight: 600; }
.article-body a { color: var(--jade); }
.article-body blockquote {
  margin: 1.25rem 0;
  padding: 0.2rem 0 0.2rem 1rem;
  border-left: 2px solid var(--brass);
  color: var(--mist);
}
.article-body table {
  width: 100%;
  border-collapse: collapse;
  margin: 1.25rem 0;
  font-size: 0.9rem;
}
.article-body th,
.article-body td {
  border-bottom: 1px solid var(--line);
  padding: 0.55rem 0.4rem;
  text-align: left;
  vertical-align: top;
}
.article-body th { color: var(--mist); }
.article-body code,
.article-body pre {
  font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
  font-size: 0.88em;
}
.article-body pre {
  overflow: auto;
  padding: 1rem;
  background: rgba(15, 28, 24, 0.9);
  border: 1px solid var(--line);
}
.article-source {
  margin-top: 3rem;
  color: rgba(217, 226, 221, 0.4);
  font-size: 0.8rem;
}

@media (max-width: 720px) {
  .topbar-nav { gap: 0.85rem; }
  .writing-row { grid-template-columns: 1fr; gap: 0.4rem; }
  .hero-actions { flex-direction: column; align-items: stretch; }
}
`,
  "site.js": `(() => {
  const rows = document.querySelectorAll(".writing-row");
  if (!("IntersectionObserver" in window) || rows.length === 0) {
    rows.forEach((row) => row.classList.add("is-in"));
    return;
  }

  const observer = new IntersectionObserver(
    (entries) => {
      for (const entry of entries) {
        if (entry.isIntersecting) {
          entry.target.classList.add("is-in");
          observer.unobserve(entry.target);
        }
      }
    },
    { rootMargin: "0px 0px -8% 0px", threshold: 0.15 },
  );

  rows.forEach((row) => observer.observe(row));

  const topbar = document.querySelector(".topbar");
  if (topbar) {
    const onScroll = () => {
      topbar.style.borderBottomColor =
        window.scrollY > 12 ? "rgba(217, 226, 221, 0.14)" : "transparent";
    };
    onScroll();
    window.addEventListener("scroll", onScroll, { passive: true });
  }
})();
`,
};
